version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-west-1 --no-include-email)
      - echo Logged in complete...
      - REPOSITORY_URI=266112834201.dkr.ecr.eu-west-1.amazonaws.com/ecs-autoface-verify-test
      - IMAGE_TAG=latest
  build:
    commands:      
      - echo DockerBuild started on `date`
      - echo Building the Docker image... 
      - docker build -t autoface_verify .
      - docker tag autoface_verify:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"autoface-verify-test-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > autoface_verify.json
artifacts:
    files: autoface_verify.json
